either/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('either/', include('votes.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

votes/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'votes'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/detail', views.detail, name='detail'),
    path('<int:pk>/detail_result', views.detail_result, name='detail_result'),
    path('<int:pk>/create_comment', views.create_comment, name='create_comment'),
    path('<int:pk>/delete', views.delete, name='delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

votes/models.py
from django.db import models

# Create your models here.
class Vote(models.Model):
    subject = models.CharField(max_length=150)
    choice_one = models.CharField(max_length=300)
    choice_two = models.CharField(max_length=300)
    vote_one = models.IntegerField(default=0)
    vote_two = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    vote = models.ForeignKey(
        Vote,
        on_delete= models.CASCADE,
    )
    choice = models.CharField(max_length=300)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    

votes/forms.py
from django import forms
from .models import Vote, Comment

class VoteForm(forms.ModelForm):
    
    subject= forms.CharField(
        widget=forms.TextInput(
            attrs={
                    'class': 'form-control'
            }
        )
    )

    choice_one = forms.CharField(
        label='First Option',
        widget=forms.TextInput(
            attrs={
                    'class': 'form-control'
            }
        )
    )

    choice_two = forms.CharField(
        label='Second Option',
        widget=forms.TextInput(
            attrs={
                    'class': 'form-control'
            }
        )
    )

    class Meta:
        model = Vote
        fields = ('subject', 'choice_one', 'choice_two')


class CommentForm(forms.ModelForm):

    choice = forms.CharField(
        label='Pick',
        widget = forms.Select(
            choices =[] ,
            attrs={
                'class':'form-control'
            }
        )
    )
    
    content = forms.CharField(
        widget = forms.TextInput(
            attrs={
                'class':'form-control'
            }
            )
    )

    class Meta:
        model = Comment
        fields = ('choice', 'content')

votes/views.py
from django.shortcuts import render, redirect
from .models import Vote, Comment
from .forms import VoteForm, CommentForm
from django import forms
from django.views.decorators.http import require_http_methods, require_safe, require_POST
import random

# Create your views here.
def index(request):
    votes = Vote.objects.all().order_by('-created_at')
    rand_vote = Vote.objects.get(pk=random.choice(Vote.objects.values_list('pk'))[0])

    context = {
        'votes':votes,
        'rand_vote':rand_vote,
    }

    return render(request, 'votes/index.html', context)


def create(request):
    if request.method == 'POST':
        form = VoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('votes:index')

    else:
        form = VoteForm()

    context = {
        'form':form
    }

    return render(request, 'votes/create.html', context)


def detail(request, pk):
    options =  [(Vote.objects.filter(pk=pk).values_list('choice_one')[0][0],Vote.objects.filter(pk=pk).values_list('choice_one')[0][0]),
         (Vote.objects.filter(pk=pk).values_list('choice_two')[0][0], Vote.objects.filter(pk=pk).values_list('choice_two')[0][0])]

    vote = Vote.objects.get(pk=pk)
    form = CommentForm()
    form.fields['choice'].widget.choices = options
    comments = vote.comment_set.all()
        

    context = {
        'vote':vote,
        'form':form,
        'comments':comments,
    }

    return render(request, 'votes/detail.html', context)


def detail_result(request, pk):
    vote = Vote.objects.get(pk=pk)
    if request.POST:
        if request.POST['choice'] == vote.choice_one:
            vote.vote_one += 1

        elif request.POST['choice'] == vote.choice_two:
            vote.vote_two += 1

        vote.save()

    options =  [(Vote.objects.filter(pk=pk).values_list('choice_one')[0][0],Vote.objects.filter(pk=pk).values_list('choice_one')[0][0]),
         (Vote.objects.filter(pk=pk).values_list('choice_two')[0][0], Vote.objects.filter(pk=pk).values_list('choice_two')[0][0])]

    form = CommentForm()
    form.fields['choice'].widget.choices = options
    comments = vote.comment_set.all()
    tot = vote.vote_one + vote.vote_two
    one_per = 0
    two_per = 0
    if tot:
        one_per = round(vote.vote_one/tot * 100,2)
        two_per = round(100 - one_per,2)

    context = {
        'vote':vote,
        'form':form,
        'comments':comments,
        'one_per':one_per,
        'two_per':two_per,
    }

    return render(request, 'votes/detail_result.html', context)


@require_POST
def create_comment(request, pk):
    vote = Vote.objects.get(pk=pk)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.vote = vote
        comment.save()

    return redirect('votes:detail', pk)


@require_POST
def delete(request, pk):
    vote = Vote.objects.get(pk=pk)
    vote.delete()

    return redirect('votes:index')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
  {% load static %}
  <title>EITHER</title>
  {% block style %}
  {% endblock %}
  
</head>
<body>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>


  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

votes/templates/votes/create.html
{% extends 'base.html' %}
{% block style %}
<style>
  button.create:hover{     
    background-color: #CCE6DF !important;
    color: #4F4B4B !important;
    transition: 0.2s ease-in-out; }
</style>
{% endblock style %}


{% block content %}
<div class="w-75 mx-auto mt-3 mb-5">
  <div class="d-flex justify-content-start align-items-baseline">
    <a href="{% url 'votes:index' %}" style="text-decoration:none; font-size:17px; color:#4F4B4B;">🏘HOME</a>
  </div>
  <div class="mx-auto d-flex justify-content-center mt-3 mb-4">
    <h2 style="font-weight:600; color:#4F4B4B;">Create Your Vote</h2>
  </div>
  <form action="" method="POST">  
    {% csrf_token %}
    {{form.as_p}}
    <div class="d-flex justify-content-end">
      <button class="btn create" style="color:white; background-color:#5A9892";>submit</button>
    </div>
  </form>
</div>
{% endblock content %}

votes/templates/votes/detail.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<style>
  button.left:hover{     
    background-color: #E25457 !important;
    color: white !important;
    transition: 0.2s ease-in-out; }
  
  button.right:hover{     
    background-color: #4E68D6 !important;
    color: white !important;
    transition: 0.2s ease-in-out; }

  .minus:hover{
    color: #E7B4C5 !important;
  }

  .play:hover{
    background-color: #E7B4C5 !important;
  }
</style>
{% endblock style %}


{% block content %}
<div class="w-75 mx-auto mt-3 mb-5">
  <div class="d-flex justify-content-between align-items-baseline">
    <a href="{% url 'votes:index' %}" style="text-decoration:none; font-size:17px; color:#4F4B4B;">🏘HOME</a>
    <form action="{% url 'votes:delete' vote.pk %}" method="POST">
      {% csrf_token %}
      <button class="btn minus" style="color:#DE3A3E; font-size:17px; font-weight:500;">DELETE</button>
    </form>
  </div>
  <br>
  
  <div class="mt-3 mb-4 d-flex flex-column justify-content-center align-items-center w-100">
    <h2 style="font-weight:600; color:#4F4B4B;">{{ vote.subject }}</h2>
  
    <div class="progress w-100 mt-4 mb-1" style="height:200px !important;">
      <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width:50%; height:100% !important;">
        <form action="{% url 'votes:detail_result' vote.pk %}" method="POST" style="width:100%; height:100% !important;">
          {% csrf_token %}
          <button class="btn left" style="width:100%; height:100%; background-color: #F2B4B5; font-weight:500; font-size:20px; color:#4D4949;" name="choice" value="{{vote.choice_one}}">{{ vote.choice_one }}</button>
        </form>
      </div>
      <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width:50%; height:100% !important;">
        <form action="{% url 'votes:detail_result' vote.pk %}" method="POST" style="width:100%; height:100% !important;">
          {% csrf_token %}
          <button class="btn right text-white" style="width:100%; height:100%; background-color: #8496E2; font-weight:500; font-size:20px;"  name="choice" value="{{vote.choice_two}}">{{ vote.choice_two }}</button>
        </form>
      </div>
    </div>
  </div>

  <div class="mx-auto mb-5 mt-5" style="width:98%;">
    <form class="mx-2" action="{% url 'votes:create_comment' vote.pk %}" method="POST">
      <div class="d-flex justify-content-between align-items-baseline mx-auto">
        <h5>Leave Comment</h5>
        <button class="btn" style="color:#5A9892; font-size:20px;"><i class="bi bi-patch-plus-fill"></i></button>
      </div>
      <hr class="mt-1 mb-3 mx-auto" style="border: 3px;">
      {% csrf_token %}
      {{form.as_p}}
    </form>
  </div>

  <div class="mx-auto", style="width:98%">
    <p class="mb-0 mx-1">Comments Here</p>
    <hr class="mt-1 mb-3 mx-auto" style="border: 2px; width:99%;">
    {% for comment in comments %}
    {% if comment.choice == vote.choice_one %}
      <div class="mx-2 my-2 d-flex align-items-center" style="background-color: #F2B4B5; border-radius:10px; overflow:hidden; height:auto;">
        <div class="mx-3 my-2">
          <small style="color:#4D4949; font-size:12px !important;">#{{ comment.choice }}#</small>
          <p style="font-size:18px; font-weight:500; color:#4D4949; margin:0;">{{ comment.content}}</p>
        </div>
      </div>
    {% else %}
      <div class="mx-2 my-2 d-flex align-items-center" style="background-color: #8496E2; border-radius:10px; overflow:hidden; height:auto;">
        <div class="mx-3 my-2">
          <small style="color:white; font-size:12px !important;">#{{ comment.choice }}#</small>
          <p style="font-size:18px; font-weight:500; color:white; margin:0;">{{ comment.content}}</p>
        </div>
    </div>
    {% endif %}
    {% endfor %}
  </div>
</div>
<br>
<br>
{% endblock content %}

votes/templates/votes/detail_result.html
{% extends 'base.html' %}


{% block content %}
<div class="w-75 mx-auto mt-3 mb-5">
  <div class="d-flex justify-content-between align-items-baseline">
    <a href="{% url 'votes:index' %}" style="text-decoration:none; font-size:17px; color:#4F4B4B;">🏘HOME</a>
    <form action="{% url 'votes:delete' vote.pk %}" method="POST">
      {% csrf_token %}
      <button class="btn minus" style="color:#DE3A3E; font-size:17px; font-weight:500;">DELETE</button>
    </form>
  </div>
  <br>

  <div class="mt-3 mb-4 d-flex flex-column justify-content-center align-items-center w-100">
    <h2 style="font-weight:600; color:#4F4B4B;">{{ vote.subject }}</h2>
    <div class="progress w-100 mt-4 mb-1" style="height:200px !important;">
      <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width:{{one_per}}%; height:100% !important; background-color: #F2B4B5 !important; font-weight:500; font-size:20px; color:#4D4949;">
        {{ vote.choice_one }}
        <br>
        {{one_per}}%
      </div>
      <div class="progress-bar progress-bar-striped bg-warning" role="progressbar" style="width:{{two_per}}%; height:100% !important; background-color: #8496E2 !important; font-weight:500; font-size:20px;">
        {{ vote.choice_two }}
        <br>
        {{two_per}}%
      </div>
    </div>
  </div>
  
  <div class="mx-auto mb-5 mt-5" style="width:98%;">
    <form class="mx-2" action="{% url 'votes:create_comment' vote.pk %}" method="POST">
      <div class="d-flex justify-content-between align-items-baseline mx-auto">
        <h5>Leave Comment</h5>
        <button class="btn" style="color:#5A9892; font-size:20px;"><i class="bi bi-patch-plus-fill"></i></button>
      </div>
      <hr class="mt-1 mb-3 mx-auto" style="border: 3px;">
      {% csrf_token %}
      {{form.as_p}}
    </form>
  </div>

  <div class="mx-auto", style="width:98%">
    <p class="mb-0 mx-1">Comments Here</p>
    <hr class="mt-1 mb-3 mx-auto" style="border: 2px; width:99%;">
    {% for comment in comments %}
    {% if comment.choice == vote.choice_one %}
      <div class="mx-2 my-2 d-flex align-items-center" style="background-color: #F2B4B5; border-radius:10px; overflow:hidden; height:auto;">
        <div class="mx-3 my-2">
          <small style="color:#4D4949; font-size:12px !important;">#{{ comment.choice }}#</small>
          <p style="font-size:18px; font-weight:500; color:#4D4949; margin:0;">{{ comment.content}}</p>
        </div>
      </div>
    {% else %}
      <div class="mx-2 my-2 d-flex align-items-center" style="background-color: #8496E2; border-radius:10px; overflow:hidden; height:auto;">
        <div class="mx-3 my-2">
          <small style="color:white; font-size:12px !important;">#{{ comment.choice }}#</small>
          <p style="font-size:18px; font-weight:500; color:white; margin:0;">{{ comment.content}}</p>
        </div>
    </div>
    {% endif %}
    {% endfor %}
  </div>
</div>
<br>
<br>
{% endblock content %}

votes/templates/votes/index.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<style>
  button.left:hover{     
    background: #E25457 !important;
    color: white !important;
    transition: 0.2s ease-in-out; }
  
  button.right:hover{     
    background: #4E68D6 !important;
    color: white !important;
    transition: 0.2s ease-in-out; }

  .plus:hover{
    color: #C88491 !important;
  }

  .play:hover{
    background-color: #E7B4C5 !important;
  }
</style>
{% endblock style %}


{% block content %}
<div class="w-75 mx-auto mt-5">
  <div style="width=40%;" class="d-flex justify-content-center mb-4">
    <img class="w-50" src="{% static 'eithergame.png' %}" alt="logo">
  </div>
  <br>
  <div class="w-100 d-flex flex-column align-items-center justify-content-center" style="border: solid 2px; border-color: #DFB7BF; border-radius: 20px; height:300px;">
    <h3>{{rand_vote.subject}}</h3>
    <div class="progress mx-auto mt-3" style="width: 95%; height:200px !important;">
      <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width:50%; height:100% !important;">
        <form action="{% url 'votes:detail_result' rand_vote.pk %}" method="POST" style="width:100%; height:100% !important;">
          {% csrf_token %}
          <button class="btn left" style="width:100%; height:100%; background-color: #F2B4B5; font-weight:500; font-size:20px; color:#4D4949;" name="choice" value="{{rand_vote.choice_one}}">{{ rand_vote.choice_one }}</button>
        </form>
      </div>
      <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width:50%; height:100% !important;">
        <form action="{% url 'votes:detail_result' rand_vote.pk %}" method="POST" style="width:100%; height:100% !important;">
          {% csrf_token %}
          <button class="btn right text-white" style="width:100%; height:100%; background-color: #8496E2; font-weight:500; font-size:20px;"  name="choice" value="{{rand_vote.choice_two}}">{{ rand_vote.choice_two }}</button>
        </form>
      </div>
    </div>
  </div>

  <div class="d-flex justify-content-between align-items-baseline mt-5 mx-auto" style="width:97%;">
    <h4 class="" style="font-weight:500;">Game LIST</h4>
    <a href="{% url 'votes:create' %}" class="plus" style="color:#E7B4C5; font-size: 28px"><i class="bi bi-patch-plus-fill"></i></a>
  </div>


  <hr class="mt-1 mb-3 mx-auto" style="border: 3px; width:98%">

  {% for vote in votes %}
  <div class="mx-auto my-2 d-flex justify-content-between align-items-center" style="border: solid 1px #BCABE2; border-radius: 10px; width:98%; height:90px;">
    <div class="d-flex flex-column mx-3">
      <h4 class="mb-1">{{ vote.subject }}</h4>
      <small>{{ vote.created_at }}</small>
    </div>
    <a href="{% url 'votes:detail' vote.pk %}" class="play btn mx-3 my-auto d-flex align-items-center justify-content-center" style="height:70%; width: 100px; background-color: #C88491; font-size:20px; color:white;">PLAY</a>
  </div>
  {% endfor %}
</div>
<br>
<br>
{% endblock content %}